name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
      - name: Upload results to Calliope
        if: always()
        run: curl -X POST
           -H "x-api-key:${{ secrets.API_KEY }}"
           -H "multipart/form-data"
           -F "file[]=@cypress/results/mochawesome*.json"
           "https://app.calliope.pro/api/v2/profile/${{ secrets.PROFILE_ID }}/import/mochawesome?tag[]=myos&tag[]=myplatform&tag[]=mybuild"
